use mcp::SkillCatalog;

pub(super) fn catalog() -> mcp::Result<SkillCatalog> {
    SkillCatalog::new()
        .with_skill(
            "homelab/investigate-observability",
            &[
                (
                    "SKILL.md",
                    include_bytes!("../skills/investigate-observability/SKILL.md"),
                ),
                (
                    "references/actions.md",
                    include_bytes!("../skills/investigate-observability/references/actions.md"),
                ),
            ],
        )?
        .with_skill(
            "homelab/operate-pipelines",
            &[
                (
                    "SKILL.md",
                    include_bytes!("../skills/operate-pipelines/SKILL.md"),
                ),
                (
                    "references/actions.md",
                    include_bytes!("../skills/operate-pipelines/references/actions.md"),
                ),
            ],
        )?
        .with_skill(
            "homelab/operate-kubernetes",
            &[
                (
                    "SKILL.md",
                    include_bytes!("../skills/operate-kubernetes/SKILL.md"),
                ),
                (
                    "references/actions.md",
                    include_bytes!("../skills/operate-kubernetes/references/actions.md"),
                ),
            ],
        )?
        .with_skill(
            "homelab/maintain-ceph",
            &[
                (
                    "SKILL.md",
                    include_bytes!("../skills/maintain-ceph/SKILL.md"),
                ),
                (
                    "references/actions.md",
                    include_bytes!("../skills/maintain-ceph/references/actions.md"),
                ),
            ],
        )?
        .with_skill(
            "homelab/manage-machines",
            &[
                (
                    "SKILL.md",
                    include_bytes!("../skills/manage-machines/SKILL.md"),
                ),
                (
                    "references/actions.md",
                    include_bytes!("../skills/manage-machines/references/actions.md"),
                ),
            ],
        )
}
